name: CI
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  GO_VERSION: 1.22.x

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Format
        run: make format

      - name: Test
        run: make test

      - name: Deploy
        run: make build
